### ISSUE TITLE
Redeploy issue on glassfish

### ISSUE THREAD

**Issue by ratcashdev** [AdamBien/porcupine#1]
deploying a maven project to glassfish (payara 1.4.151) (from NetBeans) and doing a mvn clean afterwards resulting in the following message:
`Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.4.1:clean (default-clean) on project api-server-web: Failed to clean project: Failed to delete ....\WEB-INF\lib\porcupine-0.0.4.jar`

**Comment by ratcashdev** [comment]
similar issue: https://github.com/omnifaces/omnifaces/issues/115

**Comment by AdamBien** [comment]
This is a Windows OS (and ancient) specific issue. Windows locks JARs: http://www.adam-bien.com/roller/abien/entry/re_deployment_problems_of_ears

**Comment by ratcashdev** [comment]
Meanwhile it got tracked down and resolved on Payara: 
https://github.com/payara/Payara/issues/445
