### ISSUE TITLE
How to provide my own ThreadFactory?

### ISSUE THREAD

**Issue by hugree** [AdamBien/porcupine#3]
I really  wanna use my own ThreadFactory implementation.

Is there a way to inject it into the ExecutorServiceExposer?

Thanks!

**Comment by AdamBien** [comment]
I created a test to demonstrate replacement of application-specfic test factory: https://github.com/AdamBien/porcupine/commit/0b3144194743359d6f76349d02d87571f1ff3832
Does this answer your question?

**Comment by AdamBien** [comment]
I described the extension mechanism also in the following post: [How To Replace Classes With Java EE--After The Fact](http://www.adam-bien.com/roller/abien/entry/how_to_replace_classes_with)

**Comment by hugree** [comment]
Thank you Adam! That covers it nicely. Now my tests can use a different ThreadFactory. Loving the Java EE world more and more with each minute ;)
