### ISSUE TITLE
Custom Rejection Policy doesn't update statistics

### ISSUE THREAD

**Issue by hugree** [AdamBien/porcupine#4]
I'm not sure if this is by design, but when I use a "custom" reject policy i.e. .discard or abort then the porpupine statistics module doesn't register the rejection.

This is obviously because the onRejectedExecution method is never called.

Can we have the cookie and eat it too? Provide different rejection handler and see it in the stats :)

**Comment by AdamBien** [comment]
It was a forgotten feature :-) 

It is included in the daily builds: 0.0.5-SNAPSHOT Rejections are counted regardless of the policy.

**Comment by hugree** [comment]
Are you going to release this? Believe it or not I spent like 1 hour trying to deploy it to out local nexus using ssh :)
